name: Cross-Compile and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    strategy:
      matrix:
        GOOS: [linux]
        GOARCH: [amd64, 386, arm, arm64, ppc64le, riscv64, s390x]
      max-parallel: 10

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22.10'

      - name: Cross-compile
        env:
          GOOS: ${{ matrix.GOOS }}
          GOARCH: ${{ matrix.GOARCH }}
        run: |
          mkdir dist
          GOOS=$GOOS GOARCH=$GOARCH go build -o dist/v2dat-$GOOS-$GOARCH main.go
 
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.0
          files: |
            dist/*
