name: Cross-Compile and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Generate build files
        uses: thatisuday/go-cross-build@v1
        with:
            platforms: 'linux/amd64, linux/386, linux/arm, linux/arm64, linux/ppc64le, linux/riscv64, linux/s390x'
            name: 'v2dat'
            compress: 'false'
            dest: 'dist'

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: v1.0.0
          files: |
            dist/*
