name: Cross-Compile and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm, arm64, ppc64, ppc64le, mips, mipsle, mips64, mips64le, s390, s390x]
      max-parallel: 10

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22.10'

      - name: Cross-compile for $goos-$goarch
        run: |
          GOOS=$goos GOARCH=$goarch go build -o v2dat-$goos-$goarch main.go

      - name: Archive and upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: $goos-$goarch-app
          path: $goos-$goarch-app

      - name: Create a new release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_NAME: "v${GITHUB_RUN_NUMBER}"
          RELEASE_BODY: "Automated release from GitHub Actions"
        with:
          draft: false
          prerelease: false
